evaluacion: KO
os_pre: "Windows2012"
os_post: "Windows2019"
domain_status: "En dominio"
userget: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      32666239363030323138373534626132316366363464623561633661393430666437333036663563
      3539393138323531316133326636613465373338646639610a396436323535653936366331383531
      38393034373738386664633665386262343862353862383339643237643032303566333361656634
      6535646533373864620a636538376431656161366539393735613464353930343430366266386666
      6132
userput: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37663734316336373030333136366362336465303932653030656132356466363263333931363735
      3537353533316165376434656362326639356637646562330a306235623139643838363532303631
      32353337643864353564653165623331316230656262636130386333343133373963363364653761
      3937376134396531370a333336383165366366323137636239366338613665386636313961303639
      3562
scpuser: was60
bckfile: /WebSphere80/logs/waslog.bin
rpofile: /WebSphere80/logs
passrmt: "!A2s3d4f5g"